### ISSUE TITLE
Doesn't seem to work with nodejs 0.12.3

### ISSUE THREAD

**Issue by pke** [NodeRT/NodeRT#12]
I am getting the following error:
`1>  NodeRtUtils.cpp
1>gen_code\windows.data.xml.dom\OpaqueWrapper.h(55): error C2039: 'Arguments' : is not a member of 'v8'`

**Comment by pennyfx** [comment]
Using NVM, I downloaded 0.10.31, rebuilt node-gyp and it worked.

**Comment by hgwood** [comment]
I also hit this issue. I guess this project is bound to the version of V8 found in Node 0.10.

**Comment by nadavbar** [comment]
Unfortnately today there is no support for node.js versions later than 0.10.
If you are using Windows 10 I recommend moving to use node-chakra and the node-uwp module which provides the same functionality: https://github.com/Microsoft/node-uwp

Ofcourse, I'll be more than happy to accept any contrbutions that brings this project forward to newer versions of node.js.

**Comment by TrevorDev** [comment]
Can the README.md be updated to state compatibility and to direct people to https://github.com/Microsoft/node-uwp if that is your recommendation for current developers. I spent too long trying to figure that out. I do still wish there was a way to use winRT libs with my current nodejs and build tools and without requiring me to do extra work to move so much into the microsoft stack.

**Comment by hgwood** [comment]
@nadavbar Thanks for the pointers. I indeed use Windows 10 and moved to node-uwp ([though still stuck](https://github.com/Microsoft/node-uwp/issues/11)). As @TrevorDev said, it would be a good idea to update the readme.

**Comment by nadavbar** [comment]
Thanks @TrevorDev  and @hgwood, apologies if you guys were stuck on this.

I'll update the README for now. In general the process of supporting native addons for newer version of node have become pretty problematic as the native APIs seem to change constantly (even the node abstraction layer (NAN) have recently changed) without preserving backward compatability.
The node-chakra/node-uwp solution uses a built in feature of the Chakra JS engine that enable it to automatically project UWP classes into JavaScript, hence it more robust than NodeRT (as long as you're ok with using node-chakra)

I am aware however that there are some scenarios for which you'll want UWP to work with the V8 version of node.js. Unfortantely I don't have an ETA for bringing NodeRT forward to the newer API, but I do hope to see this happen some time soon (and contributions are welcome! :) )

**Comment by TrevorDev** [comment]
:+1: thanks
