### ISSUE TITLE
Windows.Management.Deployment fails to build

### ISSUE THREAD

**Issue by Happy-Ferret** [NodeRT/NodeRT#75]
Attempting to build the above namespace for Windows 8.1 fails.

Steps to reproduce:

* Run ``NodeRTCmd.exe --winmd "C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral\Windows.winmd" --codegendir c:\NodeRT\codegen --out
dir c:\NodeRT\output --namespace Windows.Management.Deployment``
  * Result: **"Failed to build the generated project, please try to build the project manually
Generated project files are located at: c:\NodeRT\output\windows.management.deployment"**

* CD to ``c:\NodeRT\output\windows.management.deployment``.
* Run ``node-gyp rebuild``
  * Result: 
```
c:\nodert\output\windows.management.deployment\CollectionsWrap.h(442): error C2039: 'Nan::New': is not a member of 'v8::Local<v8::Object>' (compiling source file ..\_nodert_generated.cpp) [c:\
NodeRT\output\windows.management.deployment\build\binding.vcxproj]
  C:\Users\username\.node-gyp\6.10.3\include\node\v8.h(1435): note: see declaration of 'v8::Local<v8::Object>' (compiling source file ..\_nodert_generated.cpp)
  c:\nodert\output\windows.management.deployment\CollectionsWrap.h(441): note: while compiling class template member function 'void NodeRT::Collections::IterableWrapper<Windows::Management::De
  ployment::PackageUserInformation ^>::New(Nan::NAN_METHOD_ARGS_TYPE)' (compiling source file ..\_nodert_generated.cpp)
  c:\nodert\output\windows.management.deployment\CollectionsWrap.h(388): note: see reference to function template instantiation 'void NodeRT::Collections::IterableWrapper<Windows::Management::
  Deployment::PackageUserInformation ^>::New(Nan::NAN_METHOD_ARGS_TYPE)' being compiled (compiling source file ..\_nodert_generated.cpp)
  ..\_nodert_generated.cpp(1896): note: see reference to class template instantiation 'NodeRT::Collections::IterableWrapper<Windows::Management::Deployment::PackageUserInformation ^>' being co
  mpiled
c:\nodert\output\windows.management.deployment\CollectionsWrap.h(442): error C2228: left of '.ToLocalChecked' must have class/struct/union (compiling source file ..\_nodert_generated.cpp) [c:\
NodeRT\output\windows.management.deployment\build\binding.vcxproj]
c:\nodert\output\windows.management.deployment\CollectionsWrap.h(442): error C2660: 'NodeRT::Utils::SetHiddenValue': function does not take 2 arguments (compiling source file ..\_nodert_genera
ted.cpp) [c:\NodeRT\output\windows.management.deployment\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\NodeRT\output\windows.management.deployment
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
```

**Comment by nadavbar** [comment]
What version of Visual Studio are you using on your machine?
Also, can you please let me know what version of Nan is being used?

**Comment by nadavbar** [comment]
BTW, the packages that are available in the npm under the nodert-win10 scope should also work on windows 8.1 machines.

**Comment by Happy-Ferret** [comment]
NaN: 2.6.2
Visual Studio 2015 Professional

All other namespaces compile fine.

The nodert-win10 scope doesn't seem to contain the above namespace and the nodert-win8.1 scope fails to install with very much the same issue described in the OP.
